- forms/SelectInput/__tests__/SelectInput-test.js
- forms/SelectInput/index.js
- forms/SelectInput/style.scss
- forms/TextInput/index.js
- index.scss
- mixins/reactForm.mixin.js
updating with changes that were not copied from heroix and catching the last few classnames tat were not prefixed with 'hui'
> Changes Out Of Sync From Heroix Repo

- DemoPage/examples/DeltaArrow/index.js
- graphs/DeltaArrow/index.js
- graphs/DeltaArrow/style.scss
- package.json
> delta arrow supports unknown value

- forms/ImageInput/style.scss
- index.scss
- package.json
> fix image logo too big

- DemoPage/examples/DeltaArrow/index.js
- graphs/DeltaArrow/__tests__/index-test.js
- graphs/DeltaArrow/index.js
- graphs/DeltaArrow/style.scss
- package.json
> delta arrow busy

- DemoPage/examples/DataVisualisation/index.js
- graphs/DataVisualisation/SingleNumber/index.js
- graphs/DataVisualisation/SingleNumber/style.scss
- graphs/DataVisualisation/index.js
- graphs/DeltaArrow/index.js
- graphs/LineGraph/LoadingPlaceholder/index.js
- graphs/LineGraph/index.js
- package.json
> loading state

- graphs/DataVisualisation/index.js
- package.json
allow the data visualisation configure the total format.
> pass total format

- DemoPage/examples/TextInput/index.js
- forms/TextInput/style.scss
- package.json
- sass/modules/_forms.scss
> update text input readonly state

- forms/DateInput/__tests__/DateInput-test.js
- forms/DateInput/index.js
- forms/DateInput/style.scss
- package.json
> update date picker

- graphs/DeltaArrow/__tests__/index-test.js
- graphs/DeltaArrow/index.js
- package.json
> Format delta number for values over 1000

- buttons/Button/index.js
- forms/Checkbox/__tests__/Checkbox-test.js
- forms/Checkbox/index.js
- forms/DateInput/Calendar/__tests__/Calendar-test.js
- forms/DateInput/DatePickerDay/__tests__/DatePickerDay-test.js
- forms/DateInput/DatePickerDay/index.js
- forms/DateInput/DatePickerPeriod/__tests__/DatePickerPeriod-test.js
- forms/DateInput/DatePickerPeriod/index.js
- forms/DateInput/index.js
- forms/FileInput/index.js
- forms/FormRow/index.js
- forms/SelectInput/index.js
- forms/TextInput/index.js
- graphs/LineGraph/ToolTip/index.js
- layout/TopBar/index.js
- package.json
The `cx` utility will be removed in the future, it is recommended that we use this instead.
> use classnames library

- DemoPage/examples/Button/index.js
- buttons/Button/index.js
- buttons/Button/style.scss
- package.json
> borderless button

- buttons/Button/__tests__/index-test.js
- buttons/Button/index.js
- package.json
reverting to using the `onclick` event for buttons.
> use onclick for buttons

- forms/TextInput/__spec__/TextInput-spec.js
- forms/TextInput/index.js
- package.json
now textinput can really handle numbers
> fixed my stupid mistake from last time :(

- DemoPage/examples/DateSelect/index.js
- DemoPage/index.js
- assets.scss
- forms/DateSelect/__spec__/DateSelect-spec.js
- forms/DateSelect/index.js
- forms/DateSelect/style.scss
- forms/SelectInput/index.js
- forms/TextArea/style.scss
- index.scss
- mixins/reactForm.mixin.js
- package.json
- sass/_mixins.sass
> Add date select

- buttons/Button/style.scss
- forms/DateSelect/index.js
- forms/TextInput/__spec__/TextInput-spec.js
- mixins/textInput.js
- package.json
- sass/modules/_forms.scss
> Remove x icon on error

- forms/FileInput/style.scss
- sass/modules/_links.scss
> Update file input remove button

- buttons/Button/index.js
- package.json
added target property for Button to allow target to be set on link buttons
> Button Link Target

- forms/DateInput/index.js
- forms/DateSelect/index.js
- forms/FileInput/index.js
- forms/SelectInput/index.js
- forms/TextArea/index.js
- forms/TextCountDownInput/index.js
- forms/TextInput/index.js
- forms/TextInput/style.scss
- forms/UrlInput/index.js
- lib/__spec__/classNamesArray-test.js
- lib/classNamesArray.js
- package.json
Fix class name generation to exclude false string. 
fix z-index issue with inputs
Update spec path
> Fix class name generation to exclude false string. fix z-index issue with inputs

- DemoPage/examples/Button/index.js
- buttons/Button/index.js
- buttons/Button/style.scss
- forms/DateSelect/__spec__/Wrapper-spec.js
- forms/ReadOnlyAddress/index.js
- package.json
> Update borderless buttons

- DemoPage/examples/Button/index.js
- buttons/Button/style.scss
- package.json
> Update borderless button disabled css

- DemoPage/examples/ReadOnlyAddress/index.js
- forms/ImageInput/style.scss
- forms/TextInput/__spec__/TextInput-spec.js
- package.json
> Make the image logo to appear above the image input

- DemoPage/examples/TextInput/index.js
- forms/TextInput/__spec__/TextInput-spec.js
- forms/TextInput/index.js
- forms/TextInput/style.scss
- mixins/textInput.js
- package.json
> Mb add text input placeholder

- DemoPage/examples/SelectInput/index.js
- forms/SelectInput/index.js
- forms/SelectInput/style.scss
- package.json
> fix issue select input overflow for long input

- DemoPage/examples/TagList/index.js
- DemoPage/index.js
- forms/TagList/Item/__tests__/index-test.js
- forms/TagList/Item/index.js
- forms/TagList/Item/style.scss
- forms/TagList/__tests__/index-test.js
- forms/TagList/index.js
- index.scss
> Add tag list

- forms/SelectInput/style.scss
- package.json
Does not break selectInput in IE9
> Fixes text overflow problem for SelectInput

- DemoPage/examples/TagList/index.js
- assets.scss
- forms/TagList/Item/__tests__/index-test.js
- forms/TagList/__tests__/index-test.js
- forms/TagList/index.js
- forms/TagList/style.scss
- index.scss
> Added layout and spacing props to taglist

- DemoPage/examples/AvatarInput/index.js
- DemoPage/index.js
- assets.scss
- forms/AvatarInput/__tests__/AvatarInput-test.js
- forms/AvatarInput/index.js
- forms/AvatarInput/style.scss
- gulp_tasks/assets-deploy.js
- gulpfile.js
> Add avatar input.

- .eslintrc
- DemoPage/examples/Button/index.js
- buttons/Button/index.js
- buttons/Button/style.scss
- buttons/Share/__tests__/Share-test.js
- buttons/Share/index.js
- gulpfile.js
- lib/openPopup.js
> Add share button

- graphs/LineGraph/LinePath/__tests__/LinePath-test.js
- graphs/LineGraph/LinePath/index.js
- graphs/LineGraph/YScale/__tests__/YScale-test.js
- graphs/LineGraph/YScale/index.js
- graphs/LineGraph/mixins/__tests__/scaleMixin-test.js
- graphs/LineGraph/mixins/scaleMixin.js
- package.json
> [TA-6856] Allow min graph height, non zero baseline and scale units

- graphs/LineGraph/ToolTip/index.js
- graphs/LineGraph/index.js
- package.json
> [TA-6856] Improve tool tip

- DemoPage/examples/Wizard/OnboardingWizard.js
- atoms/Overlay/__tests__/Overlay-test.js
- atoms/Overlay/index.js
- atoms/Overlay/style.scss
- package.json
- wizard/Step/style.scss
Update Overlay to allow scroll
Fix border box issue
> Update Overlay to allow scroll

- DemoPage/examples/FlashMessage/index.js
- DemoPage/index.js
- assets.scss
- atoms/FlashMessage/__tests__/FlassMessage-test.js
- atoms/FlashMessage/index.js
- atoms/FlashMessage/style.scss
- package.json
- sass/_colors.scss
- sass/_variables.scss
- wizard/Step/style.scss
> Add FlashMessage

- DemoPage/examples/Wizard/OnboardingWizard.js
- package.json
- wizard/Step/style.scss
> Update wizard step styles

- DemoPage/examples/DataVisualisation/index.js
- graphs/DataVisualisation/index.js
- graphs/DataVisualisation/style.scss
> dashboard widgets show data period

- DemoPage/examples/Tabs/index.js
- DemoPage/index.js
- assets.scss
- layout/Tabs/__tests__/Tabs-test.js
- layout/Tabs/index.js
- layout/Tabs/style.scss
> Tabs component for GSC leaderboards

- DemoPage/examples/AddressFieldsetWithLookup/index.js
- DemoPage/examples/AddressLookup/index.js
- forms/AddressFieldsetWithLookup/index.js
- forms/AddressLookup/index.js
- forms/UrlSearchSelect/index.js
- forms/UrlSearchSelect/style.scss
- package.json
> Address widget should show "enter manually" on error

- DemoPage/examples/SearchInput/index.js
- DemoPage/index.js
- assets.scss
- forms/SearchInput/__tests__/Search-test.js
- forms/SearchInput/index.js
- forms/SearchInput/style.scss
- mixins/reactForm.mixin.js
- navigation/Pagination/index.js
- navigation/Pagination/style.scss
> Add search input. Update pagination count proptype

- leaderboard/LeaderboardRow/index.js
- leaderboard/LeaderboardRow/style.scss
- leaderboard/style.scss
Truncating long names. Table layout fixed (related).
> Leaderboard row changes

- DemoPage/examples/Filter/index.js
- DemoPage/index.js
- DemoPage/style.scss
- forms/Filter/__tests__/Filter-test.js
- forms/Filter/index.js
- forms/FilterSelect/__tests__/FilterSelectInput-test.js
- forms/FilterSelect/index.js
- forms/TextInput/index.js
- mixins/textInputProps.js
> Extract filter from filter select

- DemoPage/examples/Leaderboard/index.js
Location can be undefined depending on the environment.
> Fix demo page error

- forms/TextArea/index.js
propogate the 'disabled' prop all the way down to the markup of textareas to allow the textareas to actually be disabled
> Disable TextArea Prop

- package.json
> Set script name to match README

- .eslintrc
- forms/AddressFieldset/index.js
- forms/AddressFieldsetWithLookup/index.js
- forms/DateSelect/index.js
- forms/DateSelect/style.scss
- forms/FileInput/index.js
- forms/FilterSelect/index.js
- forms/FocusAggregate/__tests__/FocusAggregate-test.js
- forms/OptionList/index.js
- forms/SelectInput/index.js
- forms/TextArea/index.js
- forms/TextInput/__tests__/TextInput-test.js
- forms/TextInput/index.js
- forms/TextInput/style.scss
- forms/UrlSearchSelect/index.js
- forms/UrlSearchSelect/style.scss
- mixins/inputMessage.js
- sass/modules/_messages.scss
Should fix that weird vertical spacing issue with inputs which have either a hint or an error which isn't yet being shown.
> Input message

- DemoPage/examples/ToggleableOptionForm/index.js
- DemoPage/index.js
- assets.scss
- atoms/Icon/index.js
- forms/ToggleableOption/__tests__/ToggleableOption-test.js
- forms/ToggleableOption/i18n.js
- forms/ToggleableOption/index.js
- forms/ToggleableOption/style.css
- forms/ToggleableOptionForm/__tests__/ToggleableOptionForm-test.js
- forms/ToggleableOptionForm/index.js
- forms/ToggleableOptionForm/style.css
- forms/ToggleableOptionGroup/__tests__/ToggleableOptionGroup-test.js
- forms/ToggleableOptionGroup/index.js
- forms/ToggleableOptionGroup/style.css
- gulpfile.js
- lib/sync.js
- package.json
- test/helpers/common.js
> Add ToggleableOptionForm

- DemoPage/examples/FilterSelect/index.js
- forms/FilterSelect/Display/style.scss
- forms/TextInput/style.scss
- package.json
Update text input css with box-sizing: border-box to fix overflow issue in supporter
> Update text input css with box-sizing: border-box

- forms/TextInput/index.js
- forms/TextInput/style.scss
- mixins/textInput.js
Allows us to not output icon class for inputs which don't have icons
> Adds iconClass and hasIcon methods to textInput mixin

- forms/CopyInput/style.scss
- forms/TextInput/style.scss
> [TA-8433] CopyInput patches

- DemoPage/examples/PageContent/index.js
- DemoPage/index.js
- assets.scss
- buttons/AsyncActionToggle/__tests__/AsyncActionToggle-test.js
- buttons/AsyncActionToggle/index.js
- buttons/Button/index.js
- layout/IconBanner/__tests__/IconBanner-test.js
- layout/IconBanner/index.js
- layout/IconBanner/style.scss
- layout/PageContent/__tests__/PageContent-test.js
- layout/PageContent/index.js
- layout/PageContent/style.scss
- typography/LeadCopy/__tests__/LeadCopy-test.js
- typography/LeadCopy/index.js
- typography/LeadCopy/style.scss
> Add PageContent, IconBanner, LeadCopy, AsyncActionToggle components

- assets.scss
- atoms/Tooltip/__tests__/Tooltip-test.js
- atoms/Tooltip/index.js
- atoms/Tooltip/style.scss
- forms/ToggleableOption/index.js
- forms/ToggleableOption/style.css
- lib/bindEvents.js
- package.json
> Add Tooltips, and Tooltips on ToggleableOptions

- atoms/A/style.scss
- layout/Footer/style.scss
Some love for the footer component that currently lives in NFP. Was a bit broken in IE9.
> Improve Footer component styles in IE9

- bin/announce/released
- bin/buildkite
- bin/deploy
- bin/localkite
- Adds "released" announcement (uses BUILDKITE_MESSAGE to get the version released)
- Configures announce settings for localkite and buildkite
- Have added the slack integration env to buildkite
- Welcoming feedback on which emoji should be used to announce it :)
> Announce to slack when deployed

- layout/Footer/i18n.js
Updates footer link urls and label for United States users.
> Improve footer component for US

- .gitignore
- gulp_tasks/lint.js
- gulp_tasks/transpile.js
- gulpfile.js
- package.json
Alters our `transpile` tasks to get deploying to NPM work on the `v-3` branch.
> Fix transpilation for v-3 branch

- buttons/Button/index.js
- buttons/Button/style.scss
- sass/_colors.scss
Using these for the login buttons in supporter registrations authentication.
> Adds strava and map my fitness button kinds

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
Shamelessly stolen directly from NFP
> Adds contributing guide and PR template

- .buildkite/pipeline.yml
- bin/buildkite
- bin/deploy
- bin/localkite
Add a general description describing what this pull request acheives and any screenshots or GIF's if it includes UI changes.
- None
- None
How might the reviewer go about testing these changes?
Nope
This uses the recent only-for-version-releases script for determining if deploy should execute
- Removes BUILDKITE_MESSAGE variable from buildkite and localkite
> Use only-version-releases script for deployment

- layout/Footer/i18n.js
> Update US legal link to point to NFP terms (v3)

- layout/Footer/i18n.js
Related v3 PR: https://github.com/everydayhero/hui/pull/311
> Add US footer link localisations

- .buildkite/pipeline.yml
Add a general description describing what this pull request acheives and any screenshots or GIF's if it includes UI changes.
How might the reviewer go about testing these changes?
Any ticket/issue numbers for additional context and issue visibility.
Any additional notes or context that may help the reviewer...
A brief description of user facing changes.
> Switch pipeline to elastic queue

- .buildkite/pipeline.yml
> Restore elastic queue

- buttons/Share/index.js
> Update share button api

- buttons/Share/index.js
Add a general description describing what this pull request acheives and any screenshots or GIF's if it includes UI changes.
> Fix blundered keyname

- buttons/Share/index.js
> Fix keyname blunder and submodule weirdness

- bin/update-build-pipeline
> Submodule fix

- forms/PhoneInput/index.js
> Only expose phone number with user entry

- atoms/FlagIcon/_flags_sprite.scss
- forms/AddressFieldset/i18n.js
- forms/AddressLookup/i18n.js
- forms/AddressLookup/index.js
- forms/CountrySelect/countries.js
- forms/PhoneInput/__tests__/PhoneInput-test.js
> Replace GB with UK

- buttons/Button/style.scss
> Update button styles to disable font-ligatures

- forms/AddressFieldset/index.js
> Fix prefilled country

- bin/announce/released
No more partying. 
None
None
Make sure we the announcement doesn't bork.
None
None
Change the release announcement and drop the party parrot.
> Stop the music and go home, party parrot.

- forms/MadlibsSelect/__tests__/MadlibsSelect-test.js
- forms/MadlibsSelect/index.js
- lib/formUtils.js
Also refactored MadlibsSelect component's api to be more sensible for a generic leaf component.
> Add form utility functions

- gulp_tasks/transpile.js
> Transpile css (js styles) directory

- mixins/inputMessage.js
Reverts everydayhero/hui#388
Reverted as @benoneal added a comment while I reviewed and merged.
> Revert "Fix error display conditions"

- DemoPage/Routes/Home/index.js
- DemoPage/examples/Table/index.js
- assets.scss
- atoms/Table/__tests__/Table-test.js
- atoms/Table/index.js
- atoms/Table/style.scss
- sass/_variables.scss
Move nexus `Table` component to HUI.
> Move nexus Table component to HUI

- forms/AddressFieldsetWithLookup/index.js
- forms/UrlSearchSelect/index.js
Add a general description describing what this pull request acheives and any screenshots or GIF's if it includes UI changes.
This will stop the garbage when searching once disconnected
> [TA-10638] Use the query value to populate the default address

- layout/Masthead/index.js
> Remove the trailing space from when you join something not nothing

- forms/TextArea/index.js
- forms/TextInput/index.js
Make labels clickable (bug affected textarea because they weren't nested inside their label).
- Fix issue with clickable labels on TextArea
> Ensure for attribute of <label> is an element id

- DemoPage/examples/Checkbox/index.js
- forms/Checkbox/__tests__/Checkbox-test.js
- forms/Checkbox/index.js
- forms/Checkbox/style.scss
Also refactored checkbox component into a Stateless View.
> Add tooltip hint to checkbox

- package.json
Lets allow react-router to resolve this dependency.
> Remove history

- atoms/A/__tests__/A-test.js
> Remove only which was restricting tests

- forms/AddressFieldset/__tests__/AddressFieldset-test.js
- forms/AddressFieldset/index.js
- forms/AddressLookup/index.js
Looks like a recent PR broke the translations for these components, not surprising considering the lack of tests. 😞
> Use i18n functions to fix address fieldset translations

- forms/TextArea/index.js
- mixins/__tests__/inputMessage-test.js
- mixins/textInput.js
- mixins/textInputProps.js
- yarn.lock
Related to the feedback on this PR: https://github.com/everydayhero/hui/pull/432
> Refactor validation controlling when errors show (or don't)

- DemoPage/__tests__/DemoPage-test.js
- forms/FileInput/__tests__/FileInput-test.js
- forms/FileInput/index.js
v5 version of the following PR: https://github.com/everydayhero/hui/pull/436
> Fix filepicker mimetypes option clashing (v5)

- buttons/Button/index.js
- buttons/Button/style.scss
- sass/_colors.scss
This adds the FitBit brand color as a button color option.
None
https://edhdev.atlassian.net/browse/EM-317
This is a less than ideal process. But I'm sure we're all aware and the brand new day is not far away.
You can pass `fitbit` as an option to the button component... nifty.
> Add fitbit brand color as option for button

- buttons/Button/index.js
- forms/AvatarInput/index.js
- forms/FileInput/index.js
There's no issue releasing this as a minor I don't think as we've pinned our React (in HUI) interestingly to 15... so we're good. 
I have this a little test drive locally. Everything appeared to still work but this will need some QA in staging.
> Use function ref api for "browse files" element in File / Avatar input

- forms/AddressFieldset/__tests__/AddressFieldset-test.js
- forms/AddressFieldset/index.js
We've got sentry errors related to validations being an instance of Array. I think this might be the cause.
> Ensure that address fieldset validations are working

- forms/AddressFieldset/index.js
- forms/AddressFieldsetWithLookup/index.js
- forms/AddressLookup/index.js
- forms/CountrySelect/index.js
- package.json
The address country list was limited to 100 results when loading the initial list of countries, add max results property so all countries are displayed when the list is initially opened.
> TR-1451 Add max results property to address lookup country list
