graphs/LineGraph/XScale/index.js, graphs/LineGraph/__tests__/index-test.js
this component errors when the series contains no data. unfortunately this is the most common case for beneficiaries which have not published any events to rouse.
=> line graph handle empty data

forms/FileInput/style.scss, package.json
previously you could only click the 'browse' unless there was a placeholder or file selected.
=> clickable fileinput with no pleaceholder

forms/TextArea/index.js, forms/TextArea/style.scss
Update text input to stop resizing horizontally. Update font size. Fix label to not overrun text when scrolling.
=> TextArea updates

common.scss, package.json
explicitly loading Amatic font with HTTPS since protocol agnostic loading somehow does not laod it with https on https pages
=> Amatic Font With HTTPS

package.json
Add browserify back to allow hui to be complied correctly when used by other apps
=> Add browserify back

atoms/LoadingProgress/style.scss, package.json
This is to avoid collisions with other animations already in supporter.
=> Prefix loading indicator animations with hui

DemoPage/examples/TextInput/index.js, forms/TextInput/style.scss, mixins/textInputProps.js
Default prop `name:''` broke the labels of the inputs.
Also changes css of left-side icons to not cover entire input
=> TextInput Icons Click

DemoPage/examples/UrlSearchSelect/index.js, forms/OptionList/Item/index.js, forms/OptionList/index.js, forms/UrlSearchSelect/__tests__/URLSearchSelectInput-test.js, forms/UrlSearchSelect/index.js
Updates for UrlSearchSelect, makes sure validation are happening at the right time.
The OptionList can have focus, and it'll steal it from the Search Input, so we need to validate on blur of the "whole" component.
=> Fixes for url search select

DemoPage/examples/FilterSelect/index.js, forms/FilterSelect/Display/__tests__/Display-test.js, forms/FilterSelect/Display/index.js, forms/FilterSelect/Display/style.scss, mixins/__tests__/labelable-examples.js, mixins/labelable.js, test/helpers/common.js
Starts with FilterSelect, can add it in some more places if we like.
Adding it isn't as seamless as I'd like. The process for adding it is:
1) Add the mixin to the component you'd like to have a conditional label.
2) Use the `renderLabel` method from the mixin to render you component's label. Pass the display name of your component to it.
3) Add a class to the element of your component which would have been previously "pushed down" by the label.
4) Styles.
=> First Label-less input

forms/Filter/index.js, forms/FilterSelect/DisplayWrap/index.js, forms/FilterSelect/__tests__/FilterSelectInput-test.js, forms/FilterSelect/index.js, forms/FocusAggregate/index.js, forms/OptionList/DefaultDisplay/index.js, forms/OptionList/Item/index.js, forms/OptionList/__tests__/OptionList-test.js, forms/OptionList/index.js
Having a component for DisplayWrap and OptionList means that when they
mount they can focus
Removes the timeout for Focus aggregate, should smooth out differences
mahcine to machine
=> Refactor FilterSelect to make focus management easier

DemoPage/examples/CopyInput/index.js, DemoPage/index.js, assets.scss, docs.md, forms/CopyInput/__tests__/CopyInput-test.js, forms/CopyInput/index.js, forms/CopyInput/style.scss, forms/TextInput/__tests__/TextInput-test.js, forms/TextInput/index.js, mixins/textInput.js, package.json
Note: JS based clipboard API's aren't supported in Safari (including mobile). As a fallback the button switches to say "select", where the user can quickly press command+C or tap to view the copy/paste menu in iOS.
=> Add CopyInput component, related to [TA-8433]

forms/OptionList/Item/index.js, forms/OptionList/__tests__/OptionList-test.js
We can't use click, as it fires after blur and we use blur to close the
options list in the filter select / country select / url search select
So here we use mousedown / touch start, touchstart fires when the user
tries to scroll. To get around that triggering a selection, we keep a
var which tells us whether or not the touch has moved, if it's moved
selection wasn't intended so don't select.
=> Allow touch scrolling the option list

.buildkite/pipeline.yml, bin/deploy, docker-compose.yml
Turns out `BUILDKITE_BRANCH` was not what we thought it was when doing a bump it was always **master**, instead `BUILDKITE_MESSAGE` seems more appropriate.
From the build environment vars:
=> Use buildkite message instead of buildkite branch to trigger deploy

buttons/Button/index.js
So, weird thing, you can use the value and name of the submit buttom
from a form to provide extra params. This is used in OPGS to send the
selected OAuth provider.
https://developer.mozilla.org/en/docs/Web/HTML/Element/button
=> Add name and value props to Button

sass/modules/_forms.scss, search/AggregateSearchModal/style.scss, search/AggregateSearchResult/style.scss
After a recent update `gulp-sass` has begun complaining (rightfully) about extends that point to nowhere. This PR fixes the error by pruning them all away.
Error example:
```
events.js:85
throw er; // Unhandled 'error' event
^
Error: sass/modules/_forms.scss
Error: "%hui-text-input--readOnly" failed to @extend "%hui-text-input".
The selector "%hui-text-input" was not found.
Use "@extend %hui-text-input !optional" if the extend should be able to fail.
on line 64 of sass/modules/_forms.scss
>>   @extend %hui-text-input;
--^
```
=> Remove broken SASS extends (v3)

sass/modules/_forms.scss, search/AggregateSearchModal/style.scss, search/AggregateSearchResult/style.scss
After a recent update `gulp-sass` has begun complaining (rightfully) about extends that point to nowhere. This PR fixes the error by pruning them all away.
Error example:
```
events.js:85
throw er; // Unhandled 'error' event
^
Error: sass/modules/_forms.scss
Error: "%hui-text-input--readOnly" failed to @extend "%hui-text-input".
The selector "%hui-text-input" was not found.
Use "@extend %hui-text-input !optional" if the extend should be able to fail.
on line 64 of sass/modules/_forms.scss
>>   @extend %hui-text-input;
--^
```
Ported to `v-3` branch here: #270
=> Remove broken SASS extends

package.json
Updates `browserify` to avoid the following error when `debug: true` is set:
```
/Users/sam.enoka/Projects/hui/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275
throw new Error('Invalid mapping: ' + JSON.stringify({
^
Error: Invalid mapping: {"generated":{"line":73,"column":0},"source":"index.js","original":{},"name":null}
```
Ported to `v-3` branch: #271
=> Update browserify to fix sourcemap errors

package.json
Updates `browserify` to avoid the following error when `debug: true` is set:
```
/Users/sam.enoka/Projects/hui/node_modules/browserify/node_modules/browser-pack/node_modules/combine-source-map/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275
throw new Error('Invalid mapping: ' + JSON.stringify({
^
Error: Invalid mapping: {"generated":{"line":73,"column":0},"source":"index.js","original":{},"name":null}
```
=> Update browserify to fix sourcemap errors (v3)

gulp_tasks/transpile.js
Fixes the `Footer` component which imports `url.js` from the root of the module.
See https://github.com/everydayhero/hui/blob/master/layout/Footer/index.js#L10
=> Transpile `urls.js`

gulp_tasks/transpile.js
Fixes the `Footer` component which imports `url.js` from the root of the module.
See https://github.com/everydayhero/hui/blob/master/layout/Footer/index.js#L10
=> Transpile `urls.js` (v3)

graphs/LineGraph/index.js
Playing with some tests in NFP and noticed that this component started barking pretty loudly. Looks like jsdom has `window` defined but not `addEventListener` or `attachEvent` which leads to... issues.
=> Use bindEvents lib for friendlier testing

graphs/LineGraph/index.js
Playing with some tests in NFP and noticed that this component started barking pretty loudly. Looks like jsdom has `window` defined but not `addEventListener` or `attachEvent` which leads to... issues.
Related PR for `master`: https://github.com/everydayhero/hui/pull/293
=> Use bindEvents lib for friendlier testing (version 3)

forms/UrlSearchSelect/__tests__/URLSearchSelectInput-test.js, forms/UrlSearchSelect/index.js
This is related to the bug where the AddressSearchInput was auto-hiding when you mouse over the results. Basically, the URLSearchInput was setting the 'isOpen' state variable to whatever the 'hasError' state was on hover. If there was no error in the state, isOpen was set to false which closed the dropdown.
Expected behaviour was that if error was *true* isOpen should always be true, so I've amended the code and added specs to cover that.
Regression tests to cover the behaviour are in the pull request, however the steps to reproduce the bug prior to this fix are as below:
1. Run `supporter` locally from `master`. (Make sure you …
=> requireValue in URLSearchSelectInput was overwriting state.isOpen

docker-compose.ci.yml
After updating .pipeline to the latest, buildkite's test execution was failing due to a missing `docker-compose.ci.yml` config file.
=> Add CI docker-compose file so that Buildkite passes again

DemoPage/examples/FilterSelect/index.js, forms/FilterSelect/__tests__/FilterSelectInput-test.js, forms/FilterSelect/index.js
Add ability to sort filterSelect by label asc or desc. Defaults to options array order if no sort set
– View HUI sample page
– Find first FilterSelect 
– Results should be alphabetically sorted when you view the select and when you search
https://edhdev.atlassian.net/browse/TA-9380
FilterSelect options can now be sorted
=> Add ability to sort filterSelect by label asc or desc.

assets.scss, atoms/Tag/index.js, atoms/Tag/style.scss, forms/TagList/Item/__tests__/index-test.js, forms/TagList/Item/index.js, forms/TagList/Item/style.scss
Splits out the tag component from the tag list so that it can be re-used in isolation. Related to some work on ticket: https://edhdev.atlassian.net/browse/TA-9251
Note: Also did some general housekeeping with regards to semi-colons and ES6 syntax while I was in the neighbourhood.
Related PR for `v-3` branch: https://github.com/everydayhero/hui/pull/338
=> Split out the tag component for re-use elsewhere

assets.scss, atoms/Tag/index.js, atoms/Tag/style.scss, forms/TagList/Item/__tests__/index-test.js, forms/TagList/Item/index.js, forms/TagList/Item/style.scss
Splits out the tag component from the tag list so that it can be re-used in isolation. Related to some work on ticket: https://edhdev.atlassian.net/browse/TA-9251
Note: Also did some general housekeeping with regards to semi-colons and ES6 syntax while I was in the neighbourhood.
Related PR for `master` branch: https://github.com/everydayhero/hui/pull/337
=> Split out the tag component for re-use elsewhere (version 3)

lib/filepicker.js
This is a "I'm sick of seeing that damn error" pull request.
The story is this: certain HUI components depend on the [filepicker](https://www.filestack.com) library. It's only supplied as a script that attaches itself as `window.filepicker`. So we have a shim script that checks if it exists and exports it, so components can import it explicitly. If filepicker isn't on the window, that shim logs an error.
Problem is, the error gets logged every time HUI's built bundle loads, whether your application is using one of the Filepicker-wrapping components or not.
This PR changes the shim so that we only log the error when some code tries to call the Filepicker functions. So unless you're using one of them (in which case the error is valid and you should be loading the Filepicker library via a …
=> Enhance Filepicker error log behaviour.

bin/buildkite, bin/localkite
This PR sets up the BUILD_MESSAGE to reference the buildkite env var for use within the deploy script (originally had localkite grab the version with `$(jq -r '.version' package.json)`... but though others may not have `jq` installed)
=> Setup BUILD_MESSAGE env var for deploy

DemoPage/examples/TextInput/index.js, forms/AddressFieldset/index.js, lib/__tests__/validation-test.js, lib/validation.js, mixins/formControl.js, mixins/inputMessage.js, mixins/textInput.js, mixins/textInputProps.js
Currently HUI's textInput mixin was predicated on a single validator for any field. This PR adds a validation.compose function that composes any number of validators (either string keys matching predefined HUI validations, or custom validator functions).
The PR also includes modifications for the textInput
The reason I'm putting the PR up before it's ready to merge (I want to enhance the other inputs to allow for composed validation also) is because the current HUI mechanism for validation and error display is kind of a shitshow: it uses either `state.errorMessage`, `state.errors` (sometimes an object, sometimes an array), and `props.errors` for error display. I haven't improved this yet, just made composed validators use `state.errors`, and could use some advice on what to do to clean it …
=> Compose multiple validators (and features to apply these in TextInput)

buttons/Button/style.scss
Removes some of the fancy hover effects that use a `:before` psuedo-element in favour of simple colour transitions.
- Update the `nexus` codebase to utilise the latest version of `hero-ui`
How might the reviewer go about testing these changes?
Jira ticket: https://edhdev.atlassian.net/browse/TA-10125
This comes after some lengthy testing and discussions that ended in favour of simplifying animations to ensure a consistent experience for all users without the need for hacks and work-arounds on behalf of the downstream consumer of `hero-ui`.
=> [TA-10125] Simplify button hover to avoid transition rendering bugs in Chrome

buttons/Button/style.scss
This solves a bug where if the button us focused the text became white by default, which was illegible in some circumstances, example:
=> Ensure hover effects have focus counterparts

mixins/inputMessage.js
This fix adds a few more sanity checks for 'shouldDisplayError' so that it doesn't attempt to display the error box if there is no `errors` or `errorMessage` prop set. (For example, the Address search widget sets 'hasError' to display the error icon in the field, but the actual error messages are hooked up to the dropdown component.)
=> Fix error display conditions

layout/Masthead/__tests__/Masthead-test.js, layout/Masthead/index.js
Allow Masthead component to take customised logos. If `imagePath` is set it will pick up the path and ignore the logo you provided, so this should not break our existing application.
=> Allow masthead to take customised logo

forms/AddressFieldsetWithLookup/index.js
This is a bit of a Hail Mary. It fixed the issue on Android Chrome, which was rendering with its `state.address` as null even though `getInitialState` returns a valid address in `this.props.prefill`. Manually calling setState with that prop before mounting fixes the initial setup, however when I removed that code everything was *still* working, even after I killed local storage.
So I'm confused.
In a working system, this is just a redundant setting of the initial address, so it shouldn't hurt anything.
=> Force android to respect initial address when prefill prop exists

mixins/localStorage.js
This was already handled in Supporter's `localStorage` mixin, but HUI either didn't have it (or it was removed). Basically, there is a specific scenario where `window.localStorage` exists, but if you try to save anything it throws a `QuotaExceededException` DOM error. Since our React components don't handle for that and use localStorage in lifecycle methods, it kills the initial render of most of the form components.
The specific scenario we have encountered is any version of Safari in Private Browsing mode, but it's a standard exception for Local Storage so it may happen in other places.
This PR adds silent opt-out of local storage features if saving would result in the aforementioned exception.
=> localStorage exception when saving kills React render

forms/UrlSearchSelect/__tests__/URLSearchSelectInput-test.js
This test was super wack and holding up PR's; Passing locally but failing on buildkite. For whatever reason a `__jsonp` key was being included in the object that `mockGetJSON` is called with...
As a small fix using `calledWithMatch` will be less strict and not care about extra keys.
Also fixed some terrible whitespace.
=> Patch flickering test with calledWithMatch

DemoPage/Routes/Home/index.js, DemoPage/examples/Tooltip/index.js, assets.scss, atoms/Tooltip/__tests__/Tooltip-test.js, atoms/Tooltip/index.js, atoms/Tooltip/style.scss, atoms/TooltipContent/__tests__/TooltipContent-test.js, atoms/TooltipContent/index.js, atoms/TooltipContent/style.scss
Extends the existing `Tooltip` component to be more flexible in the positioning, colour and trigger mechanism.
- Where previously the `Tooltip` component took a `text` prop it now takes a prop called `content`. This change was made to be more generic given the tooltip can display richer content, such as formatted text, links or images.
- The `side` prop has also been renamed, it is now `position`. This is because the tooltip now supports being set to `'center'` as well as the `'left'` and `'right'`.
- Tooltips can be triggered by click or hover.
- The tooltip still uses a question mark icon as the default trigger, but you can wrap the tooltip around any other text, component or node to change the trigger.
- Tooltips can be set to either dark or light variants, where the background and …
=> [TA-10462] Refactor and extend Tooltip component

README.md
The generic `npm run <script>` will output copious amounts of debug
information when the script exits with a failure status. Since tests are
expected to fail, the `npm test` entry point should be used to run tests
as it will suppress this output.
=> Recommend `npm test` instead of `npm run test`

forms/AddressFieldsetWithLookup/index.js, forms/AddressLookup/index.js, forms/UrlSearchSelect/__tests__/URLSearchSelectInput-test.js, forms/UrlSearchSelect/index.js
This solves a problem which we surfaced in `warp-gate` with the `AddressFieldsetWithLookup` component. If the user doesn't even touch the address search field then no errors are shown – turns out the thing just didn't accept `errors` or `errorMessage` props making it unlike every other form input component in HUI.
=> Allow error props to be passed down to URLSearchSelectInput

Dockerfile, yarn.lock
Resolves some weird environment issues seen in builds between `yarn` and `node-sass`:
```sh
[4/4] Building fresh packages...
error /usr/src/app/node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/install.js
Directory: /usr/src/app/node_modules/node-sass
Output:
path.js:7
throw new TypeError('Path must be a string. Received ' + inspect(path));
^
TypeError: Path must be a string. Received undefined
at assertPath (path.js:7:11)
at Object.join (path.js:1211:7)
at /usr/src/app/node_modules/node-sass/scripts/install.js:122:26
at /usr/src/app/node_modules/mkdirp/index.js:30:20
at FSReqWrap.oncomplete (fs.js:117:15)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a …
```
=> Include Yarn lockfile along with package.json in Dockerfile

forms/TextInput/index.js, mixins/inputMessage.js, mixins/reactForm.mixin.js, mixins/textInput.js
Hopefully the last piece of Supporter to come across to HUI from today. This allows inputs to collect error messages for multiple validations onto their local state, and renders them if they exist when showing validation messages.
=> Port show errors from local state behaviour from Supporter

forms/CopyInput/__tests__/CopyInput-test.js, forms/CopyInput/index.js, mixins/inputMessage.js, test/helpers/testdom.js
Missed a couple of edge checks in the nasty nasty supporter code that prevent error messages from rendering while you're editing a field.
=> Get the edge cases on error rendering working

gulp_tasks/lint.js
The `lint` gulp task currently spits a bunch of lint errors which clog up the console, this PR resolves that.
=> Ignore transpiled code when linting

atoms/A/__tests__/A-test.js, atoms/A/index.js
HUI's Footer component has a bunch of <A /> components with a href but no onClick set. This is fine, but the <A /> handler has onClick as optional but always calls it, meaning you get an undefined prop exception on every Footer click.
This fixes that.
=> Fix exception firing when option <A /> onClick handler not set

buttons/Share/index.js, lib/openPopup.js
In iOS and (probably Android) browsers, we can't guarantee that the reference to the window that `window.open` creates will stick around. Users can close the tab and kill the reference, or the tab can be unloaded from memory due to low-memory devices.
This means checking `windowRef.closed` will often result in an undefined property error. This fix takes care of that.
=> In openPopup, support losing a reference to a closed window

mixins/textInputProps.js
So, this looks like a pretty innocuous.
In `warp-gate` we find ourselves in a position where we aren't using the `onError` callback out of the box and thus these lines give us some trouble:
https://github.com/everydayhero/hui/blob/master/mixins/textInput.js#L45-L48
```js
if (onError && validate && required) {
const { valid, messages } = getValidator(validate)(value)
onError(!valid, messages)
}
```
In earlier versions of HUI this has resulted in validations being run twice when we would expect them to only run once. And in the latest version of HUI we run in to errors because `getValidator` returns undefined.
I'm curious to understand if it's safe to simply not use a noop by default.
=> Default textInput onError prop to null making it fully opt-in

forms/AddressFieldset/__tests__/AddressFieldset-test.js, forms/AddressFieldset/index.js, mixins/formControl.js
We have some logic around dirty fields and need to expose `onBlur` for each field. See test for example usage.
=> Expose onBlur callback for address fields

mixins/textInput.js
In `warp-gate` we are seeing some pretty terrible performance due to inputs being validated every time props change. Likely because the form has quite a few inputs compared to most existing usages.
Tried doing a straight up comparison between `nextProps` and `this.props` but at any given time there are a tonne of props that we don't care about.
From what I can tell there are only a few prop changes that really matter and would warrant the subsequent logic to execute.
Also shifted initial validation to happen on mount. After some testing on the demo page a bit this surprisingly didn't change behaviour. I was worried that running validation on mount would cause errors to display immediately but they don't.
=> Run validation logic only when specific prop changes are detected

sass/modules/_forms.scss
The disabled text input area is not visible on Safari like below: 
After the change:
=> Fix disabled input text invisible on Safari

forms/AddressFieldset/__tests__/AddressFieldset-test.js, forms/AddressFieldset/i18n.js, forms/AddressFieldset/index.js
Related to #429 restores functionality where switching region changes the labels.
=> Ensure address fieldset labels are regionalised

forms/AddressFieldset/index.js
When multiple `AddressFieldset` components appear on the page together the refs can sometimes clash. This currently causes problems in Safari browser.
=> Prefix field refs to avoid onFocus bugs

.eslintrc, DemoPage/__tests__/DemoPage-test.js, forms/FileInput/__tests__/FileInput-test.js, forms/FileInput/index.js
Using the built in `extension` and `extensions` options with `FileInput` currently causes an error as it is incompatible with the `mimetypes` option.
From the filepicker docs regarding extension options:
> Specify the type of file that the user is allowed to pick by extension. *Do not use this option with mimetype(s) specified as well*.
https://www.filepicker.com/docs/file-ingestion/javascript-api/pick?v=v2
This PR resolves that error by only setting the `mimetypes` option if the `extension` or `extensions` are not defined.
I will duplicate this work over on the master v5 branch shortly.
=> Fix filepicker mimetypes option clashing (v4)

package.json
According to the commits on the react functional repo the only change is the update to react 15.
=> Update react-functional so we don't have react@0.14 anywhere as a dep

forms/FilterSelect/Display/style.scss, sass/modules/_forms.scss
If a label spanned 2 lines, which is reasonable on smaller viewports,
there was a few problems...
1) the line height on the label meant the lines were way too close
2) no extra space was left to show the selected value, which meant it
often displayed underneath the label
**Before**
**After**
None
None
I just ran the docs locally, and tested the FilterSelect component with labels of various length.
https://edhdev.atlassian.net/browse/PS-3698
This issue has been reported by a couple of clients who are using groups, and due to the layout of the one page get started form, the form fields aren't very wide, and many group value …
=> Fix issue with FilterSelect labels that span multiple lines

DemoPage/examples/TextInput/index.js, assets.scss, forms/SimpleSelectInput/index.js, forms/SimpleSelectInput/style.scss, forms/TextInput/index.js, forms/TextInput/style.scss
This is some garbage code. HUI's styles are basically un-enhanceable, so the best course of action for 'do something in HUI that is similar but not quite the same as existing inputs' is to copy/paste and modify the new component.
I need this new SimpleSelectInput component as a child of TextInput for the new manual fitness UI refit.
Generates the below component:
=> Allow compound text and dropdown inputs

forms/FocusAggregate/index.js
I'm not able to recreate them, but we have a few errors in sentry that
_might_ be related to methods being called on objects which have been
"cleaned up" ready for reuse. I don't know if this is something react
does. The idea is to try and make this a little more reasonable (it's
not totally reasonable because the job it's doing is pretty weird). I
doubt this will have any effect of on those errors ... but if it does:
super.
The job of the FocusAggregate is to call it's onBlur handler only once in the case of a stream of `blur, focus, blur` events. Why? Because this way we get a blur event when hovering over or keyboard nav-ing through a list of radio buttons (the OptionList). Why do we care about focus? …
=> Scope blurring timer in FocusAggregate per instance

mixins/formControl.js
We're getting a lot of errors in Sentry about onBlur not being a function for the Filter Select component. Being that it's pretty hard to see exactly where this is coming from I'm adding this pretty innoucuous (I think) change. Woot.
=> Ensure field methods are Functions

forms/AddressLookup/index.js, forms/AddressLookup/style.scss
We're no longer using Google for address lookup, because they're now really expensive. We're now using only Loqate (used to be Postcode Anywhere, same company) in every region. This means the "Powered by Google" branding required in non-UK regions is no longer required.
=> Remove isGoogleLookup and branding from AddressLookup list.
